version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"

    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: db
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_PASSWORD: db
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
